columnSuffix: null
contentColumnType: string
fieldGroup: f476ca1f-3ad0-4d18-8499-2b9f582b7c7d
handle: formie
instructions: ''
name: Formie
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
