columnSuffix: zbmisorc
contentColumnType: text
fieldGroup: 5dc06c33-c87b-41ae-a550-20ccfa75033f
handle: oiThumbnail
instructions: ''
name: 'Opt Img Thumbnail'
searchable: false
settings:
  displayDominantColorPalette: '1'
  displayLazyLoadPlaceholderImages: '1'
  displayOptimizedImageVariants: '1'
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '0'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '992'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '0'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '768'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '0'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '0'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
