columnSuffix: null
contentColumnType: text
fieldGroup: f476ca1f-3ad0-4d18-8499-2b9f582b7c7d
handle: vizyPagebuilder
instructions: ''
name: ' Vizy Pagebuilder'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
  trimEmptyParagraphs: '1'
  vizyConfig: ''
translationKeyFormat: null
translationMethod: none
type: verbb\vizy\fields\VizyField
