fieldLayouts:
  cc36d3d4-a5c9-4cab-be83-0ecfc47d7916:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 300d2d1c-6e37-4f2c-a4ef-fb19b059131b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c40d22bf-e52e-472a-a0f6-2a3f363cf0d1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Optimized Images'
        sortOrder: 2
handle: images
hasUrls: true
name: Images
settings:
  bucket: $SPACES_BUCKET
  contentDisposition: ''
  endpoint: $SPACES_ENDPOINT
  expires: ''
  keyId: $SPACES_API_KEY
  region: $SPACES_REGION
  secret: $SPACES_SECRET
  subfolder: $SPACES_SUBFOLDER
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: vaersaagod\dospaces\Volume
url: $SPACES_URL
