dateModified: 1642090085
email:
  fromEmail: taylor+craftvue@ellcreative.com
  fromName: Nuxt
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    76566381-39cb-4a0a-979e-9ba75b430b12: Common # Common
    e06c8337-4b69-45aa-95f7-d6faf18148c0: Nuxt # Nuxt
    e50799a7-aaec-4292-8d59-1231573c09c0: Nuxt # Nuxt
system:
  edition: solo
  live: true
  name: Nuxt
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
