dateModified: 1642799468
email:
  fromEmail: taylor+craftvue@ellcreative.com
  fromName: Nuxt
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    12c7facb-5f44-4a34-a722-5152910e42d2: Page # Page
    21c395ab-0cfe-4302-b582-b40c41f0ce69: Main # Main
    33c95d46-1b63-46e7-9d39-cec478b7f04c: ' Neo Pagebuilder' #  Neo Pagebuilder
    168e8e0b-765a-48af-8234-2e44e6af6099: ' Vizy Pagebuilder' #  Vizy Pagebuilder
    76566381-39cb-4a0a-979e-9ba75b430b12: Common # Common
    a19a9d6a-7e70-4dd0-b337-7fc490c001ec: Pages # Pages
    abfe13f7-402d-41ab-a4bd-c29c8f252846: Pagebuilders # Pagebuilders
    ac430f3b-b3b3-45ea-817f-f6db630d243b: Copy # Copy
    b3e1d1ca-562d-48d1-9935-82d27aa939d9: 'Public Schema' # Public Schema
    c4f69099-6417-4a7d-be20-0b550f49a92c: Image # Image
    cc0d7245-f9a3-4fa5-be24-2c18a3535146: New # New
    e06c8337-4b69-45aa-95f7-d6faf18148c0: Nuxt # Nuxt
    e9cad64a-269f-458b-983e-4f839f117801: Frontend # Frontend
    e50799a7-aaec-4292-8d59-1231573c09c0: Nuxt # Nuxt
    e97237b2-ce7a-444a-863b-bd1fd92322ae: 'Contact Form' # Contact Form
    f0a279c3-748c-4f1c-8859-800205bc4fb2: Form # Form
plugins:
  architect:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  cloner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.7
    settings:
      originalNavHash:
        __assoc__:
          -
            - ae9bb02b-549b-45ad-8df0-88aeaae241dd
            - W3sibGFiZWwiOiJEYXNoYm9hcmQiLCJ1cmwiOiJkYXNoYm9hcmQiLCJmb250SWNvbiI6ImdhdWdlIn0seyJsYWJlbCI6IkVudHJpZXMiLCJ1cmwiOiJlbnRyaWVzIiwiZm9udEljb24iOiJzZWN0aW9uIn0seyJsYWJlbCI6Ikdsb2JhbHMiLCJ1cmwiOiJnbG9iYWxzIiwiZm9udEljb24iOiJnbG9iZSJ9LHsibGFiZWwiOiJDYXRlZ29yaWVzIiwidXJsIjoiY2F0ZWdvcmllcyIsImZvbnRJY29uIjoiY2F0ZWdvcmllcyJ9LHsibGFiZWwiOiJVc2VycyIsInVybCI6InVzZXJzIiwiZm9udEljb24iOiJ1c2VycyJ9LHsibGFiZWwiOiJBcmNoaXRlY3QiLCJ1cmwiOiJhcmNoaXRlY3QiLCJpY29uIjoiL2FwcC92ZW5kb3IvcGVubmViYWtlci9jcmFmdC1hcmNoaXRlY3Qvc3JjL2ljb24tbWFzay5zdmcifSx7ImxhYmVsIjoiRmVlZCBNZSIsInVybCI6ImZlZWQtbWUiLCJpY29uIjoiL2FwcC92ZW5kb3IvY3JhZnRjbXMvZmVlZC1tZS9zcmMvaWNvbi1tYXNrLnN2ZyJ9LHsibGFiZWwiOiJGaWVsZCBNYW5hZ2VyIiwidXJsIjoiZmllbGQtbWFuYWdlciIsImljb24iOiIvYXBwL3ZlbmRvci92ZXJiYi9maWVsZC1tYW5hZ2VyL3NyYy9pY29uLW1hc2suc3ZnIn0seyJsYWJlbCI6IkZvcm1pZSIsInVybCI6ImZvcm1pZSIsImljb24iOiIvYXBwL3ZlbmRvci92ZXJiYi9mb3JtaWUvc3JjL2ljb24tbWFzay5zdmciLCJzdWJuYXYiOnsiZm9ybXMiOnsibGFiZWwiOiJGb3JtcyIsInVybCI6ImZvcm1pZS9mb3JtcyJ9LCJzdWJtaXNzaW9ucyI6eyJsYWJlbCI6IlN1Ym1pc3Npb25zIiwidXJsIjoiZm9ybWllL3N1Ym1pc3Npb25zIn0sInNlbnROb3RpZmljYXRpb25zIjp7ImxhYmVsIjoiU2VudCBOb3RpZmljYXRpb25zIiwidXJsIjoiZm9ybWllL3NlbnQtbm90aWZpY2F0aW9ucyJ9LCJzZXR0aW5ncyI6eyJsYWJlbCI6IlNldHRpbmdzIiwidXJsIjoiZm9ybWllL3NldHRpbmdzIn19fSx7ImxhYmVsIjoiRnJlZWZvcm0iLCJ1cmwiOiJmcmVlZm9ybSIsImljb24iOiIvYXBwL3ZlbmRvci9zb2xzcGFjZS9jcmFmdC1mcmVlZm9ybS9wYWNrYWdlcy9wbHVnaW4vc3JjL2ljb24tbWFzay5zdmciLCJiYWRnZUNvdW50IjoxLCJzdWJuYXYiOnsiZGFzaGJvYXJkIjp7ImxhYmVsIjoiRGFzaGJvYXJkIiwidXJsIjoiZnJlZWZvcm0vZGFzaGJvYXJkIn0sInN1Ym1pc3Npb25zIjp7ImxhYmVsIjoiU3VibWlzc2lvbnMiLCJ1cmwiOiJmcmVlZm9ybS9zdWJtaXNzaW9ucyJ9LCJzcGFtIjp7ImxhYmVsIjoiU3BhbSIsInVybCI6ImZyZWVmb3JtL3NwYW0ifSwiZm9ybXMiOnsibGFiZWwiOiJGb3JtcyIsInVybCI6ImZyZWVmb3JtL2Zvcm1zIn0sImZpZWxkcyI6eyJsYWJlbCI6IkZpZWxkcyIsInVybCI6ImZyZWVmb3JtL2ZpZWxkcyJ9LCJub3RpZmljYXRpb25zIjp7ImxhYmVsIjoiRW1haWwgTm90aWZpY2F0aW9ucyIsInVybCI6ImZyZWVmb3JtL25vdGlmaWNhdGlvbnMifSwic2V0dGluZ3MiOnsibGFiZWwiOiJTZXR0aW5ncyIsInVybCI6ImZyZWVmb3JtL3NldHRpbmdzIn0sInJlc291cmNlcyI6eyJsYWJlbCI6IlJlc291cmNlcyIsInVybCI6ImZyZWVmb3JtL3Jlc291cmNlcyJ9fX0seyJsYWJlbCI6Ik5hdmlnYXRpb24iLCJ1cmwiOiJuYXZpZ2F0aW9uIiwiaWNvbiI6Ii9hcHAvdmVuZG9yL3ZlcmJiL25hdmlnYXRpb24vc3JjL2ljb24tbWFzay5zdmcifSx7ImxhYmVsIjoiUmV0b3VyIiwidXJsIjoicmV0b3VyIiwiaWNvbiI6Ii9hcHAvdmVuZG9yL255c3R1ZGlvMTA3L2NyYWZ0LXJldG91ci9zcmMvaWNvbi1tYXNrLnN2ZyIsInN1Ym5hdiI6eyJkYXNoYm9hcmQiOnsibGFiZWwiOiJEYXNoYm9hcmQiLCJ1cmwiOiJyZXRvdXIvZGFzaGJvYXJkIn0sInJlZGlyZWN0cyI6eyJsYWJlbCI6IlJlZGlyZWN0cyIsInVybCI6InJldG91ci9yZWRpcmVjdHMifSwic2V0dGluZ3MiOnsibGFiZWwiOiJTZXR0aW5ncyIsInVybCI6InJldG91ci9zZXR0aW5ncyJ9fX0seyJsYWJlbCI6IlNFT21hdGljIiwidXJsIjoic2VvbWF0aWMiLCJpY29uIjoiL2FwcC92ZW5kb3IvbnlzdHVkaW8xMDcvY3JhZnQtc2VvbWF0aWMvc3JjL2ljb24tbWFzay5zdmciLCJzdWJuYXYiOnsiZGFzaGJvYXJkIjp7ImxhYmVsIjoiRGFzaGJvYXJkIiwidXJsIjoic2VvbWF0aWMvZGFzaGJvYXJkIn0sImdsb2JhbCI6eyJsYWJlbCI6Ikdsb2JhbCBTRU8iLCJ1cmwiOiJzZW9tYXRpYy9nbG9iYWwvZ2VuZXJhbCJ9LCJjb250ZW50Ijp7ImxhYmVsIjoiQ29udGVudCBTRU8iLCJ1cmwiOiJzZW9tYXRpYy9jb250ZW50In0sInNpdGUiOnsibGFiZWwiOiJTaXRlIFNldHRpbmdzIiwidXJsIjoic2VvbWF0aWMvc2l0ZS9pZGVudGl0eSJ9LCJ0cmFja2luZyI6eyJsYWJlbCI6IlRyYWNraW5nIFNjcmlwdHMiLCJ1cmwiOiJzZW9tYXRpYy90cmFja2luZy9ndGFnIn0sInBsdWdpbiI6eyJsYWJlbCI6IlBsdWdpbiBTZXR0aW5ncyIsInVybCI6InNlb21hdGljL3BsdWdpbiJ9fX0seyJsYWJlbCI6IldlYnBlcmYiLCJ1cmwiOiJ3ZWJwZXJmIiwiaWNvbiI6Ii9hcHAvdmVuZG9yL255c3R1ZGlvMTA3L2NyYWZ0LXdlYnBlcmYvc3JjL2ljb24tbWFzay5zdmciLCJiYWRnZUNvdW50IjoiIiwic3VibmF2Ijp7ImRhc2hib2FyZCI6eyJsYWJlbCI6IkRhc2hib2FyZCIsInVybCI6IndlYnBlcmYvZGFzaGJvYXJkIn0sInBlcmZvcm1hbmNlIjp7ImxhYmVsIjoiUGVyZm9ybWFuY2UiLCJ1cmwiOiJ3ZWJwZXJmL3BlcmZvcm1hbmNlIn0sImVycm9ycyI6eyJsYWJlbCI6IkVycm9ycyAiLCJ1cmwiOiJ3ZWJwZXJmL2Vycm9ycyIsImJhZGdlIjoiIn0sInNldHRpbmdzIjp7ImxhYmVsIjoiU2V0dGluZ3MiLCJ1cmwiOiJ3ZWJwZXJmL3NldHRpbmdzIn19fSx7ImxhYmVsIjoiR3JhcGhRTCIsInVybCI6ImdyYXBocWwiLCJpY29uIjoiQGFwcGljb25zL2dyYXBocWwuc3ZnIiwic3VibmF2Ijp7InNjaGVtYXMiOnsibGFiZWwiOiJTY2hlbWFzIiwidXJsIjoiZ3JhcGhxbC9zY2hlbWFzIn0sInRva2VucyI6eyJsYWJlbCI6IlRva2VucyIsInVybCI6ImdyYXBocWwvdG9rZW5zIn0sImdyYXBoaXFsIjp7ImxhYmVsIjoiR3JhcGhpUUwiLCJ1cmwiOiJncmFwaGlxbCIsImV4dGVybmFsIjp0cnVlfX19LHsidXJsIjoidXRpbGl0aWVzIiwibGFiZWwiOiJVdGlsaXRpZXMiLCJmb250SWNvbiI6InRvb2wiLCJiYWRnZUNvdW50Ijo3fSx7InVybCI6InNldHRpbmdzIiwibGFiZWwiOiJTZXR0aW5ncyIsImZvbnRJY29uIjoic2V0dGluZ3MifSx7InVybCI6InBsdWdpbi1zdG9yZSIsImxhYmVsIjoiUGx1Z2luIFN0b3JlIiwiZm9udEljb24iOiJwbHVnaW4ifV0=
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: 9DD3EHCB00KSL545GKULL6GD
    schemaVersion: 1.2.6
  freeform:
    edition: lite
    enabled: true
    licenseKey: 67HYCIG67ILTB6ZDKE735COS
    schemaVersion: 3.5.1
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: 55TI59YOF52A5G7IF2TBQ7AT
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: UQJVZ6TKP4LJW1TEQDBYLVL1
    schemaVersion: 1.0.21
  neo:
    edition: standard
    enabled: true
    licenseKey: HILWCZZ034TDLEZJUP7G6FBZ
    schemaVersion: 2.11.6
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: 96ZPN0B0IBZ00ZY11AIAVIOL
    schemaVersion: 3.0.10
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 3KFFKI3D1J79JB6JLFFR55WZ
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: true
      enableMetaContainerEndpoint: true
      enableSeoFileLinkEndpoint: true
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: false
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  similar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  snitch:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  vizy:
    edition: standard
    enabled: true
    licenseKey: 7ZU5NURA9OX4LOHAUSRDX7LU
    schemaVersion: 0.9.0
  webperf:
    edition: standard
    enabled: true
    licenseKey: SVCR8N666M56DHR88XXWBXFG
    schemaVersion: 1.0.1
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
