childBlocks: null
field: 7837b255-d91e-41bf-a6ec-68c15a5c9ab4 #  Page Builder
fieldLayouts:
  8c9dc6a2-25ef-4141-a88e-de7b53f2ff11:
    tabs:
      -
        elements:
          -
            fieldUid: 20672a1b-d265-4cad-8b42-ad0c93d5c3eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6473523-8b96-4e45-97f1-916f256aa5d3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: copy
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Copy
sortOrder: 5
topLevel: false
