childBlocks: null
field: 7837b255-d91e-41bf-a6ec-68c15a5c9ab4 #  Page Builder
fieldLayouts:
  087f47fa-0cd2-4f2e-8a4a-9f6fedec874e:
    tabs:
      -
        elements:
          -
            fieldUid: 941fe563-7eed-4240-925c-4fa24a53f7fe # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: image
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Image
sortOrder: 7
topLevel: false
