childBlocks:
  - column
field: 7837b255-d91e-41bf-a6ec-68c15a5c9ab4 #  Neo Page Builder
handle: twoColumn
maxBlocks: 0
maxChildBlocks: 2
maxSiblingBlocks: 0
name: 'Two Column'
sortOrder: 2
topLevel: false
